#pragma once

#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX, UNICODE_MODE_MACOS

/* Unicode characters */
#define A_CIRC UP(A_CIRCUMFLEX_LOWER, A_CIRCUMFLEX_UPPER) /* â Â */
#define E_CIRC UP(E_CIRCUMFLEX_LOWER, E_CIRCUMFLEX_UPPER) /* ê Ê */
#define I_CIRC UP(I_CIRCUMFLEX_LOWER, I_CIRCUMFLEX_UPPER) /* î Î */
#define O_CIRC UP(O_CIRCUMFLEX_LOWER, U_CIRCUMFLEX_UPPER) /* ô Ô */
#define U_CIRC UP(U_CIRCUMFLEX_LOWER, U_CIRCUMFLEX_UPPER) /* û Û */

#define E_DIAE UP(E_DIAERESIS_LOWER, E_DIAERESIS_UPPER) /* ë Ë */
#define I_DIAE UP(I_DIAERESIS_LOWER, I_DIAERESIS_UPPER) /* ï Ï */
#define O_DIAE UP(O_DIAERESIS_LOWER, O_DIAERESIS_UPPER) /* ö Ö */
#define U_DIAE UP(U_DIAERESIS_LOWER, U_DIAERESIS_UPPER) /* ü Ü */

#define A_GRAV UP(A_GRAVE_LOWER, A_GRAVE_UPPER) /* à À */
#define E_GRAV UP(E_GRAVE_LOWER, E_GRAVE_UPPER) /* è È */
#define U_GRAV UP(U_GRAVE_LOWER, U_GRAVE_UPPER) /* ù Ù */

#define E_ACUT UP(E_ACUTE_LOWER, E_ACUTE_UPPER) /* é É */

#define C_CEDI UP(C_CEDILLA_LOWER, C_CEDILLA_UPPER) /* ç Ç */

#define AE UP(AE_LOWER, AE_UPPER) /* æ Æ */
#define OE UP(OE_LOWER, OE_UPPER) /* œ Œ */
#define SHARP_S UP(SHARP_S_LOWER, SHARP_S_UPPER) /* ß ẞ */
#define MU UP(MU_LOWER, MU_UPPER) /* µ M */
#define THRDOTS UM(THREEDOTS) /* … */
#define LNGDASH UM(ENDASH) /* – */

enum unicode_names {
    A_CIRCUMFLEX_LOWER,
    A_CIRCUMFLEX_UPPER,
    E_CIRCUMFLEX_LOWER,
    E_CIRCUMFLEX_UPPER,
    I_CIRCUMFLEX_LOWER,
    I_CIRCUMFLEX_UPPER,
    O_CIRCUMFLEX_LOWER,
    O_CIRCUMFLEX_UPPER,
    U_CIRCUMFLEX_LOWER,
    U_CIRCUMFLEX_UPPER,

    E_DIAERESIS_LOWER,
    E_DIAERESIS_UPPER,
    I_DIAERESIS_LOWER,
    I_DIAERESIS_UPPER,
    O_DIAERESIS_LOWER,
    O_DIAERESIS_UPPER,
    U_DIAERESIS_LOWER,
    U_DIAERESIS_UPPER,

    A_GRAVE_LOWER,
    A_GRAVE_UPPER,
    E_GRAVE_LOWER,
    E_GRAVE_UPPER,
    U_GRAVE_LOWER,
    U_GRAVE_UPPER,

    E_ACUTE_LOWER,
    E_ACUTE_UPPER,

    C_CEDILLA_LOWER,
    C_CEDILLA_UPPER,

    AE_LOWER,
    AE_UPPER,

    OE_LOWER,
    OE_UPPER,

    SHARP_S_LOWER,
    SHARP_S_UPPER,

    MU_LOWER,
    MU_UPPER,

    THREEDOTS,

    ENDASH
};

const uint32_t PROGMEM unicode_map[] = {
    [A_CIRCUMFLEX_LOWER] = 0x00E2,
    [A_CIRCUMFLEX_UPPER] = 0x00C2,
    [E_CIRCUMFLEX_LOWER] = 0x00EA,
    [E_CIRCUMFLEX_UPPER] = 0x00CA,
    [I_CIRCUMFLEX_LOWER] = 0x00EE,
    [I_CIRCUMFLEX_UPPER] = 0x00CE,
    [O_CIRCUMFLEX_LOWER] = 0x00F4,
    [O_CIRCUMFLEX_UPPER] = 0x00D4,
    [U_CIRCUMFLEX_LOWER] = 0x00FB,
    [U_CIRCUMFLEX_UPPER] = 0x00DB,

    [E_DIAERESIS_LOWER] = 0x00EB,
    [E_DIAERESIS_UPPER] = 0x00CB,
    [I_DIAERESIS_LOWER] = 0x00EF,
    [I_DIAERESIS_UPPER] = 0x00CF,
    [O_DIAERESIS_LOWER] = 0x00F6,
    [O_DIAERESIS_UPPER] = 0x00D6,
    [U_DIAERESIS_LOWER] = 0x00FC,
    [U_DIAERESIS_UPPER] = 0x00DC,

    [A_GRAVE_LOWER] = 0x00E0,
    [A_GRAVE_UPPER] = 0x00C0,
    [E_GRAVE_LOWER] = 0x00E8,
    [E_GRAVE_UPPER] = 0x00C8,
    [U_GRAVE_LOWER] = 0x00F9,
    [U_GRAVE_UPPER] = 0x00D9,

    [E_ACUTE_LOWER] = 0x00E9,
    [E_ACUTE_UPPER] = 0x00C9,

    [C_CEDILLA_LOWER] = 0x00E7,
    [C_CEDILLA_UPPER] = 0x00C7,

    [AE_LOWER] = 0x00E6,
    [AE_UPPER] = 0x00C6,

    [OE_LOWER] = 0x0153,
    [OE_UPPER] = 0x0152,

    [SHARP_S_LOWER] = 0x00DF,
    [SHARP_S_UPPER] = 0x1E9E,

    [MU_LOWER] = 0x03BC,
    [MU_UPPER] = 0x004D,

    [THREEDOTS] = 0x2026,

    [ENDASH] = 0x2013
};
