#pragma once

enum unicode_names {
    A_CIRCUMFLEX_LOWER,
    A_CIRCUMFLEX_UPPER,
    E_CIRCUMFLEX_LOWER,
    E_CIRCUMFLEX_UPPER,
    I_CIRCUMFLEX_LOWER,
    I_CIRCUMFLEX_UPPER,
    O_CIRCUMFLEX_LOWER,
    O_CIRCUMFLEX_UPPER,
    U_CIRCUMFLEX_LOWER,
    U_CIRCUMFLEX_UPPER,

    E_DIAERESIS_LOWER,
    E_DIAERESIS_UPPER,
    O_DIAERESIS_LOWER,
    O_DIAERESIS_UPPER,
    U_DIAERESIS_LOWER,
    U_DIAERESIS_UPPER,

    A_GRAVE_LOWER,
    A_GRAVE_UPPER,
    E_GRAVE_LOWER,
    E_GRAVE_UPPER,
    U_GRAVE_LOWER,
    U_GRAVE_UPPER,

    E_ACUTE_LOWER,
    E_ACUTE_UPPER,

    C_CEDILLA_LOWER,
    C_CEDILLA_UPPER
};

const uint32_t PROGMEM unicode_map[] = {
    [A_CIRCUMFLEX_LOWER] = 0x00E2,
    [A_CIRCUMFLEX_UPPER] = 0x00C2,
    [E_CIRCUMFLEX_LOWER] = 0x00EA,
    [E_CIRCUMFLEX_UPPER] = 0x00CA,
    [I_CIRCUMFLEX_LOWER] = 0x00EE,
    [I_CIRCUMFLEX_UPPER] = 0x00CE,
    [O_CIRCUMFLEX_LOWER] = 0x00F4,
    [O_CIRCUMFLEX_UPPER] = 0x00D4,
    [U_CIRCUMFLEX_LOWER] = 0x00FB,
    [U_CIRCUMFLEX_UPPER] = 0x00DB,

    [E_DIAERESIS_LOWER] = 0x00EB,
    [E_DIAERESIS_UPPER] = 0x00CB,
    [O_DIAERESIS_LOWER] = 0x00F6,
    [O_DIAERESIS_UPPER] = 0x00D6,
    [U_DIAERESIS_LOWER] = 0x00FC,
    [U_DIAERESIS_UPPER] = 0x00DC,

    [A_GRAVE_LOWER] = 0x00E0,
    [A_GRAVE_UPPER] = 0x00C0,
    [E_GRAVE_LOWER] = 0x00E8,
    [E_GRAVE_UPPER] = 0x00C8,
    [U_GRAVE_LOWER] = 0x00F9,
    [U_GRAVE_UPPER] = 0x00D9,

    [E_ACUTE_LOWER] = 0x00E9,
    [E_ACUTE_UPPER] = 0x00C9,

    [C_CEDILLA_LOWER] = 0x00E7,
    [C_CEDILLA_UPPER] = 0x00C7
};
